// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DIRECT_URL: 마이그레이션용 direct connection (db.xxx.supabase.co:5432)
    // DATABASE_URL: 런타임용 pooler (pooler.supabase.com:6543) — PrismaClient에서 사용
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
